# Generated by Django 5.0.7 on 2024-07-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('callsign', models.CharField(max_length=100)),
                ('founded_year', models.PositiveIntegerField()),
                ('base_airport', models.CharField(max_length=100)),
            ],
        ),
    ]
